### ISSUE TITLE
TypeError in Python3 

### ISSUE THREAD

**Issue by karthikeyan-dhandapani** [aruba/aruba-central-ansible-role#5]
Description:
TypeError when using "+" operand for type(dict_items) + type(dict_items)

https://github.com/aruba/aruba-central-ansible-role/blob/6203de0a8e4d86997ae81304bb76e7336e759dd2/library/central_sites.py#L413

https://github.com/aruba/aruba-central-ansible-role/blob/6203de0a8e4d86997ae81304bb76e7336e759dd2/library/central_sites.py#L415

**Comment by jayp193** [comment]
Thanks @timway for picking it up.

**Comment by jayp193** [comment]
Thanks for adding this @timway
